---
- name: Install Oracle 19c and Create Database on Production Server
  hosts: prod
  vars:
    db_name: prod.localdomain
    db_sid: PROD
    sys_password: Oracle123
  roles:
    - oracle_install

- name: Install Oracle 19c and Create Database on Test Server
  hosts: test
  vars:
    db_name: test.localdomain
    db_sid: TEST
    sys_password: Oracle123
  roles:
    - oracle_install
